"""
output/report.py — HTML & JSON export.
Venom green identity. Matches terminal design system.
"""

import json
import datetime
from pathlib import Path

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Viper Report — {target}</title>
<style>
:root{{
  --bg:#080808;--s:#0e0e0e;--b:#1a1a1a;
  --green:#22c55e;--green-d:#16a34a;--green-x:#14532d;
  --cy:#06b6d4;--tx:#c8c8c8;--dm:#555;
  --red:#ef4444;--yw:#eab308;--wh:#f5f5f5;
}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:var(--bg);color:var(--tx);font:13px/1.7 'Courier New',monospace;padding:2.5rem}}
header{{border-bottom:1px solid var(--green-x);padding-bottom:1.5rem;margin-bottom:2rem}}
.logo{{font-size:1.5rem;color:var(--green);font-weight:700;letter-spacing:.2em}}
.tag{{color:var(--dm);font-size:.8rem;margin-top:.2rem;letter-spacing:.1em}}
.meta{{color:var(--dm);font-size:.82rem;margin-top:1rem}}
.meta b{{color:var(--cy)}}
.stats{{display:flex;gap:1rem;margin-bottom:2.5rem;flex-wrap:wrap}}
.stat{{background:var(--s);border:1px solid var(--b);border-left:2px solid var(--green-x);padding:.8rem 1.4rem;min-width:110px}}
.sv{{font-size:2rem;color:var(--green);font-weight:700}}
.sl{{font-size:.7rem;color:var(--dm);margin-top:.1rem;letter-spacing:.12em}}
h2{{
  color:var(--green);font-size:.78rem;letter-spacing:.2em;text-transform:uppercase;
  margin:2.5rem 0 .8rem;display:flex;align-items:center;gap:.5rem
}}
h2::before{{content:'⟡';color:var(--green-d)}}
h2::after{{content:'';flex:1;height:1px;background:var(--green-x);margin-left:.5rem}}
.table-wrap{{overflow-x:auto}}
table{{width:100%;border-collapse:collapse;font-size:.83rem}}
th{{
  background:var(--s);color:var(--dm);text-align:left;
  padding:.4rem .8rem;font-size:.72rem;letter-spacing:.12em;
  border-bottom:1px solid var(--b);
}}
td{{padding:.4rem .8rem;border-bottom:1px solid var(--b)}}
tr:hover td{{background:var(--s)}}
.port{{color:var(--green);font-weight:700}}
.open{{color:var(--green)}}
.svc{{color:var(--wh)}}
.crit{{color:var(--red);font-weight:700}}
.high{{color:#f97316}}
.med{{color:var(--yw)}}
.low{{color:var(--dm)}}
.cve{{color:var(--wh)}}
.sub{{color:var(--cy)}}
.ip{{color:var(--dm)}}
.flag{{color:var(--yw);margin-left:.4rem}}
a{{color:var(--cy);text-decoration:none}}
a:hover{{text-decoration:underline}}
.tag-open{{color:var(--green);font-weight:700}}
.tag-crit{{color:var(--red);font-weight:700}}
footer{{margin-top:3rem;color:var(--dm);font-size:.75rem;border-top:1px solid var(--b);padding-top:1rem}}
</style>
</head>
<body>
<header>
  <div class="logo">VIPER</div>
  <div class="tag">we bite.</div>
  <div class="meta">target <b>{target}</b> &nbsp;·&nbsp; {timestamp} &nbsp;·&nbsp; v0.2.0</div>
</header>

<div class="stats">
  <div class="stat"><div class="sv">{n_ports}</div><div class="sl">OPEN PORTS</div></div>
  <div class="stat"><div class="sv">{n_vulns}</div><div class="sl">VULNS</div></div>
  <div class="stat"><div class="sv">{n_subs}</div><div class="sl">SUBDOMAINS</div></div>
  <div class="stat"><div class="sv">{n_social}</div><div class="sl">SOCIAL HITS</div></div>
</div>

{body}

<footer>Generated by Viper CLI — authorized use only.</footer>
</body>
</html>"""


def _section(icon: str, title: str, rows: str) -> str:
    return f"<h2>{title}</h2>\n<div class='table-wrap'>{rows}</div>\n"


def _ports(ports: list) -> str:
    if not ports:
        return "<div style='color:var(--dm);padding:.5rem 0'>No open ports.</div>"
    rows = []
    for p in ports:
        flag = "<td><span class='flag'>▲ flagged</span></td>" if p.get('flagged') else "<td></td>"
        row = "<tr>" + f"<td class='port'>{p['port']}</td><td class='open'>OPEN</td><td class='svc'>{p.get('service','')}</td>" + flag + "</tr>"
        rows.append(row)
    joined = "".join(rows)
    return f"<table><thead><tr><th>PORT</th><th>STATE</th><th>SERVICE</th><th></th></tr></thead><tbody>{joined}</tbody></table>"


def _vulns(vulns: list) -> str:
    if not vulns:
        return "<div style='color:var(--dm);padding:.5rem 0'>No findings.</div>"
    sev_order = {"CRIT": 0, "HIGH": 1, "MED": 2, "LOW": 3}
    rows = "".join(
        f"<tr>"
        f"<td class='{v['severity'].lower()}'>{v['severity']}</td>"
        f"<td class='cve'>{v['cve']}</td>"
        f"<td>{v['desc']}</td>"
        f"<td class='ip'>{str(v.get('banner',''))[:40]}</td>"
        f"</tr>"
        for v in sorted(vulns, key=lambda x: sev_order.get(x.get("severity",""), 9))
    )
    return f"<table><thead><tr><th>SEV</th><th>CVE</th><th>DESCRIPTION</th><th>BANNER</th></tr></thead><tbody>{rows}</tbody></table>"


def _subs(subs: list) -> str:
    if not subs:
        return "<div style='color:var(--dm);padding:.5rem 0'>No subdomains found.</div>"
    rows = "".join(
        f"<tr><td class='sub'>{s['subdomain']}</td><td class='ip'>{s['ip']}</td></tr>"
        for s in subs
    )
    return f"<table><thead><tr><th>SUBDOMAIN</th><th>IP</th></tr></thead><tbody>{rows}</tbody></table>"


def _social(hits: list) -> str:
    if not hits:
        return "<div style='color:var(--dm);padding:.5rem 0'>No profiles found.</div>"
    rows = "".join(
        f"<tr><td class='svc'>{h['platform']}</td><td><a href='{h['url']}'>{h['url']}</a></td></tr>"
        for h in hits
    )
    return f"<table><thead><tr><th>PLATFORM</th><th>URL</th></tr></thead><tbody>{rows}</tbody></table>"


def render_html(data: dict, path: str):
    body = ""
    if data.get("ports"):
        body += _section("▲", "Port Scan", _ports(data["ports"]))
    if data.get("vulns"):
        body += _section("✕", "Vulnerabilities", _vulns(data["vulns"]))
    if data.get("subs"):
        body += _section("◈", "Subdomains", _subs(data["subs"]))
    if data.get("social"):
        body += _section("⟡", "Social Profiles", _social(data["social"]))
    if not body:
        body = "<div style='color:var(--dm)'>No scan data found in this file.</div>"

    html = HTML.format(
        target=data.get("target", "unknown"),
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        n_ports=len(data.get("ports", [])),
        n_vulns=len(data.get("vulns", [])),
        n_subs=len(data.get("subs", [])),
        n_social=len(data.get("social", [])),
        body=body,
    )
    Path(path).write_text(html, encoding="utf-8")


def render_json(data: dict, path: str):
    data["generated"] = datetime.datetime.now().isoformat()
    Path(path).write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
